config/routes.rb
OverThereApp::Application.routes.draw do

  resources :postcodes

  resources :main, only: [:index], as: '/'

  resources :boroughs, only: [:index, :show]

  root to: 'main#index'

  resources :clients

end

app/models/borough.rb
class Borough < ActiveRecord::Base
  attr_accessible :anxiety_score, :average_age, :crime_rates_per_capita, :employment_rate, :first_largest_immigrant_group, :gross_annual_pay, :happiness_score, :inner_outer, :life_satisfaction_score, :name, :percent_cycling_adults, :percent_greenspace, :political_control, :population, :population_density, :population_percent_foreign, :population_percent_senior, :population_percent_working, :population_percent_youth, :second_largest_immigrant_group, :third_largest_immigrant_group, :worthwhileness_score, :latitude, :longitude, :location

  has_many :postcodes

  reverse_geocoded_by :latitude, :longitude, address: :location
  after_validation :reverse_geocode


end

app/models/client.rb
class Client < Foursquare2::Client
  # attr_accessible :lat, :lon

  def initialize
    super(:client_id => 'LRDVJ31Z3N2GREGOT5X4UA1BASUZJGW5VNMUOL3GXNRAKM3P', :client_secret => 'R34UO3K0KBD12KFEOCNZLJJCPSM2TF1PMTD4Q11SY431KN1L', :api_version => '20120505')
  end

end

app/models/postcode.rb
class Postcode < ActiveRecord::Base
  attr_accessible :borough_id, :latitude, :longitude, :postcode
  belongs_to :borough

  geocoded_by :address
  after_validation :geocode
  after_create :find_borough

  def find_borough
    borough = Borough.near(self).first.id
    self.update_attributes(borough_id: borough)
  end

  def address
    "London, #{postcode}"
  end

  def ranking
    ranking = 0

    if self.count_high_street_coffee < 10
      ranking += 1
    end

    if self.count_high_street_bikes > 5
      ranking += 1
    end

    if self.check_place(types: "restaurant", keyword: "vegan").count > 1
      ranking += 1
    end
    ranking

  end

  def check_place(options = {})
    client = GooglePlaces::Client.new("AIzaSyCUwtN6QKlS5rxeXhS6gUcQgH4LqiUqyXQ")

    client.spots(latitude, longitude, options.merge({radius: 1000}))
  end

  def count_high_street_coffee
    coffee_shops = ["starbucks", "nero", "eat", "pret", "costa", "dunkin"]
    shop_count = []
    coffee_shops.each do |shop|
      shop_count << check_place(name: shop, types: "cafe").count
    end
    shop_count.inject(0, :+)
  end

  def count_high_street_bikes
    bike_shops = ["evans", "surgery", "halfords"]
    shop_count = []
    bike_shops.each do |shop|
      shop_count << check_place(name: shop, types: "bicycle_store").count
    end
    shop_count.inject(0, :+)
  end

  def instagram
    min_timestamp = 1.week.ago.to_time.to_i
    max_timestamp = Time.new.to_time.to_i
    distance = 1000
    url = "https://api.instagram.com/v1/media/search?lat=#{latitude}&lng=#{longitude}&min_timestamp=#{min_timestamp}&max_timestamp=#{max_timestamp}&distance=#{distance}&access_token=8035257.052c85c.fbc9ded6488c44e2a7be19a7687bb6e7"
    @hash = HTTParty.get(url)["data"] rescue nil
    @hash || {}
  end

  def growth_average
    return @growth_average if @growth_average
    search_zoopla
    @growth_average
  end

  def growth_median
    return @growth_median if @growth_median
    search_zoopla
    @growth_median
  end

  private
  def search_zoopla
    ps = postcode.to_s.downcase.tr(" ", "+")

    url ="http://api.zoopla.co.uk/api/v1/average_sold_prices.json?postcode=#{ps}&output_type=outcode&area_type=postcodes&api_key=ckj3rw3k4hjh3xhtptht52ab"
    response = HTTParty.get(url)
    areas = response['areas'] rescue nil
        
    prices = areas.map { |area| area['average_sold_price_1year'].to_i }
    five_year_prices = areas.map { |area| area['average_sold_price_5year'].to_i }

    sum_1_year = prices.inject{|sum,x| sum + x}
    length_1_year = prices.length
    sort_1_year = prices.sort
    sum_5_year = five_year_prices.inject{|sum,x| sum + x}
    length_5_year = five_year_prices.length
    sort_5_year = five_year_prices.sort

    median_1_year = (sort_1_year[(length_1_year - 1) / 2] + sort_1_year[length_1_year / 2]) / 2.0
    average_1_year = sum_1_year / length_1_year
    median_5_year = (sort_5_year[(length_5_year - 1) / 2] + sort_5_year[length_5_year / 2]) / 2.0
    average_5_year = sum_5_year / length_5_year

    @growth_average = ((((average_5_year - average_1_year).to_f) / average_1_year.to_f) * 100).round(2)
    @growth_median = ((((median_5_year - median_1_year).to_f) / median_1_year.to_f) * 100).round(2)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def index
    
  end

  def show
    
  end

end

app/controllers/boroughs_controller.rb
class BoroughsController < ApplicationController

  # Boroughs controller added only for purpose of working out partials.
  # Should be deleted afterwards.
  
  def index
    @boroughs = Borough.all
  end

  def show
    @borough = Borough.find(params[:id])
  end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  
  def index
    @postcode = Postcode.find(params[:id])
    c = Client.new
    @clients = c.search_venues_by_tip(:ll => "#{@postcode.latitude},#{@postcode.longitude}", :query => 'hipster', :limit => 20)
  end

end

app/controllers/main_controller.rb
class MainController < ApplicationController
  
  def index
    @postcode = Postcode.new
  end



  def search

  end

end

app/controllers/postcodes_controller.rb
class PostcodesController < ApplicationController
  
  def create
    user_pc = params[:postcode][:postcode]
    pc = UKPostcode.new(user_pc)
    if pc.valid?
      postcode = pc.outcode

      if Postcode.where(postcode: postcode).empty?
        @postcode = Postcode.create(postcode: postcode)

        respond_to do |format|
          if @postcode.save
            format.html { redirect_to @postcode}
          else
            format.html { render 'main#index'}
          end
        end
      else
        redirect_to postcode_path(Postcode.where(postcode: postcode).first)
      end
    else
      flash[:notice] = "Invalid postcode, try again."
      redirect_to root_path
    end
  end

  def show
    @postcode = Postcode.find(params[:id])

    @instagram = @postcode.instagram
    
    c = Client.new
    @clients = c.search_venues_by_tip(:ll => "#{@postcode.latitude},#{@postcode.longitude}", :radius => 1000,:query => 'hipster', :limit => 20)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boroughs_helper.rb
module BoroughsHelper
end

app/views/boroughs/_borough.html.haml
%h1
  = @borough.name
%br
#borough-show-left
  %h3 Population Demographics
  %br
  %ul
    %li.population_percent_youth
      Youth Population 
    %li.population_percent_working
      Working Age Population
    %li.population_percent_senior
      Senior Age Population
    %li.population_percent_foreign
      Foreign Born Population
  %br
  %canvas{id: "myChart", width: "400", height:"400"}
  %br
  %h3 Three Largest Foreign Nationalities
  %ul
    %li.first-largest
      =@borough.first_largest_immigrant_group
    %li.second-largest
      =@borough.second_largest_immigrant_group
    %li.third-largest
      =@borough.third_largest_immigrant_group
  %br
  %h3
    Greenspace as a %age of total land: 
    = "#{@borough.percent_greenspace}%"
  - if @borough.percent_greenspace > 80
    = render partial: 'greenspace-svg', locals: {size: "500px"}
  - elsif @borough.percent_greenspace > 50%
    = render partial: 'greenspace-svg', locals: {size: "300px"}
  - elsif @borough.percent_greenspace > 30%
    = render partial: 'greenspace-svg', locals: {size: "200px"}
  - else
    = render partial: 'greenspace-svg', locals: {size: "100px"}

#borough-show-right
  %h3 Each represents approximately 10,000 people
  %br
  - (@borough.population.to_i / 10000).times do
    = render 'people-svg'
  %br
  %h3 Each represents crime per 10,000 people
  %br
  - (@borough.crime_rates_per_capita.to_i / 10).times do
    = render 'crime-svg'

:javascript
      var ctx = $("#myChart").get(0).getContext("2d");
      var data = [ 
        {
          value : #{@borough.population_percent_youth},
          color: "#5FBEBE"
        },
        {
          value : #{@borough.population_percent_working},
          color: "#98C79A"
        },
        {
          value : #{@borough.population_percent_senior},
          color: "#6997B1"
        },
        {
          value : #{@borough.population_percent_foreign},
          color: "#A7BB75"
        }
      ];

  new Chart(ctx).PolarArea(data, {
    scaleOverride: true,
    //** Required if scaleOverride is true **
    //Number - The number of steps in a hard coded scale
    scaleSteps : 8,
    //Number - The value jump in the hard coded scale
    scaleStepWidth : 10,
    //Number - The centre starting value
    scaleStartValue : 0
  });

app/views/boroughs/_crime-svg.html.erb
<svg class="crime" version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
   width="80.551px" height="100px" viewBox="9.724 0 80.551 100" enable-background="new 9.724 0 80.551 100" xml:space="preserve">
<g id="Layer_1_1_">
  <g>
    <path d="M59.562,43.206L49.288,32.932h9.104l3.574,6.192v3.254c0,2.944,2.321,5.356,5.229,5.504v-0.244V34.33l-3.186-5.517
      l10.562,6.098c2.771,1.6,6.315,0.651,7.917-2.121l-14.768-8.526h11.969c3.201,0,5.796-2.595,5.796-5.794H67.299l5.172-2.986
      c2.332-1.346,3.234-4.229,2.171-6.638L58.021,18.44l-0.048,0.028H34.824L16.356,0L9.724,19.163l41.642,24.043l8.194,8.194
      C61.823,49.138,61.823,45.469,59.562,43.206z"/>
    <path d="M86.85,61.635l1.492-5.571l-25.078-6.719L59.97,61.635h-3.924v28.484L73.16,100l17.115-9.881V61.635H86.85z M64.7,51.832
      l21.153,5.669l-1.107,4.134H62.074L64.7,51.832z"/>
  </g>
</g>
<g id="Layer_1_copy" display="none">
  <path display="inline" d="M74.824,27.615H45.587l-6.718,3.878v5.033l0.272,0.158h26.135C70.383,36.684,74.568,32.658,74.824,27.615
    z"/>
  <polygon display="inline" points="-40.196,27.615 -3.405,27.615 -38.523,-19.006 -63.815,23.194 -40.687,36.547 -40.687,27.615   
    "/>
  <path display="inline" d="M10.59,66.152L23.154,82.83l0.782-0.59c4.858-3.658,5.833-10.59,2.173-15.447L15.49,52.696h-28.207
    L10.59,66.152z"/>
  <path display="inline" d="M38.87,48.129l15.413,8.899c4.806,2.774,10.952,1.128,13.728-3.679L50.604,43.301l-11.461-6.617H38.87
    V48.129z"/>
  <polygon display="inline" points="38.87,36.684 39.142,36.684 38.87,36.525   "/>
  <polygon display="inline" points="24.112,52.696 29.801,62.55 29.801,52.696  "/>
  <path display="inline" d="M35.85,73.026l-6.049-10.478v6.281c0,5.106,4.025,9.291,9.069,9.547v-2.06
    C37.659,75.458,36.615,74.352,35.85,73.026z"/>
  <polygon display="inline" points="38.87,36.525 38.87,31.492 34.511,34.009   "/>
  <polygon display="inline" points="33.088,36.684 33.088,44.792 38.87,48.129 38.87,36.684   "/>
  <polygon display="inline" points="33.088,34.831 33.088,36.684 38.87,36.684 38.87,36.525 34.511,34.009   "/>
  <path display="inline" d="M33.088,52.696h-3.288v9.854l6.049,10.478c0.765,1.324,1.809,2.431,3.02,3.292V56.197l-5.781-10.014
    V52.696z"/>
  <path display="inline" d="M40.685,27.615l8.969-5.178c4.043-2.334,5.61-7.334,3.764-11.513l-19.45,11.229v5.462H40.685z"/>
  <polygon display="inline" points="29.801,27.389 29.411,27.615 29.801,27.615   "/>
  <polygon display="inline" points="38.87,31.492 45.587,27.615 38.87,27.615   "/>
  <polygon display="inline" points="28.186,27.615 33.968,27.615 33.968,22.153 24.899,27.389 24.899,27.615   "/>
  <polygon display="inline" points="33.088,27.615 33.088,33.188 34.511,34.009 38.87,31.492 38.87,27.615   "/>
  <polygon display="inline" points="34.511,34.009 33.088,33.188 33.088,34.831   "/>
  <polygon display="inline" points="12.812,46.537 8.768,39.532 13.704,36.684 3.427,36.684 15.49,52.696 24.112,52.696 
    18.62,43.184  "/>
  <polygon display="inline" points="13.704,36.684 14.577,36.178 12.778,33.065 11.689,32.437 12.052,31.808 11.014,30.009 
    14.129,28.21 14.474,27.615 -3.405,27.615 3.427,36.684   "/>
  <polygon display="inline" points="29.411,27.615 23.434,27.615 26.422,29.339   "/>
  <polygon display="inline" points="-40.196,36.684 -40.196,27.615 -40.687,27.615 -40.687,36.547 -12.717,52.696 15.49,52.696 
    3.427,36.684  "/>
  <polygon display="inline" points="-40.196,36.684 3.427,36.684 -3.405,27.615 -40.196,27.615  "/>
  <polygon display="inline" points="29.801,40.49 29.801,36.729 28.171,37.668  "/>
  <polygon display="inline" points="11.689,32.437 12.778,33.065 12.052,31.808   "/>
  <polygon display="inline" points="15.161,27.615 14.474,27.615 14.129,28.21  "/>
  <polygon display="inline" points="24.127,30.664 26.422,29.339 23.434,27.615 22.367,27.615   "/>
  <polygon display="inline" points="29.801,42.893 24.462,39.811 18.62,43.184 24.112,52.696 29.801,52.696  "/>
  <polygon display="inline" points="11.014,30.009 12.052,31.808 14.129,28.21  "/>
  <polygon display="inline" points="12.778,33.065 14.577,36.178 16.374,35.141   "/>
  <polygon display="inline" points="28.171,37.668 24.462,39.811 29.801,42.893 29.801,40.49  "/>
  <polygon display="inline" points="24.127,30.664 22.367,27.615 15.161,27.615 14.129,28.21 12.052,31.808 12.778,33.065 
    16.374,35.141   "/>
  <polygon display="inline" points="29.801,36.729 29.801,40.49 31.882,44.096 33.088,44.792 33.088,36.684 29.879,36.684  "/>
  <polygon display="inline" points="29.879,36.684 33.088,36.684 33.088,34.831   "/>
  <polygon display="inline" points="29.801,42.893 29.801,52.696 33.088,52.696 33.088,46.184 31.882,44.096   "/>
  <polygon display="inline" points="29.801,40.49 29.801,42.893 31.882,44.096  "/>
  <polygon display="inline" points="13.704,36.684 8.768,39.532 12.812,46.537 18.62,43.184 14.867,36.684   "/>
  <polygon display="inline" points="29.801,31.29 29.801,27.615 29.411,27.615 26.422,29.339  "/>
  <polygon display="inline" points="14.577,36.178 13.704,36.684 14.867,36.684   "/>
  <polygon display="inline" points="27.603,36.684 28.171,37.668 29.801,36.729 29.801,36.684   "/>
  <polygon display="inline" points="29.801,36.684 29.801,31.29 26.422,29.339 24.127,30.664 27.603,36.684  "/>
  <polygon display="inline" points="14.867,36.684 18.62,43.184 24.462,39.811 19.043,36.684  "/>
  <polygon display="inline" points="19.043,36.684 16.374,35.141 14.577,36.178 14.867,36.684   "/>
  <polygon display="inline" points="27.603,36.684 19.043,36.684 24.462,39.811 28.171,37.668   "/>
  <polygon display="inline" points="19.043,36.684 27.603,36.684 24.127,30.664 16.374,35.141   "/>
  <polygon display="inline" points="33.088,27.615 29.801,27.615 29.801,31.29 33.088,33.188  "/>
  <polygon display="inline" points="29.801,36.729 29.879,36.684 29.801,36.684   "/>
  <polygon display="inline" points="29.879,36.684 33.088,34.831 33.088,33.188 29.801,31.29 29.801,36.684  "/>
</g>
</svg>

app/views/boroughs/_greenspace-svg.html.erb
<svg class="greenspace" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" id="Layer_1" x="0px" y="0px" width=<%= size %> height=<%= size %> viewBox="0 0 100 100" enable-background="new 0 0 100 100" xml:space="preserve">
<g>
  <g>
    <path d="M93.075,32.489c0,0,2.321-11-1.814-15.823c-4.524-5.271-13.723-5.407-13.723-5.407S72.206,4.034,65.43,2.848    c-8.472-1.484-17.557,0.2-17.557,0.2s-5.199-4.613-16.547-2.603c-8.5,1.504-9.284,10.415-9.284,10.415s-7.755-0.263-10.896,4.006    c-3.406,4.628,0.202,14.42,0.202,14.42s-4.626,6.458-3.229,12.218c1.213,5.002,8.475,5.207,8.475,5.207s1.392,7.898,7.669,8.212    c5.121,0.254,10.696-2.604,10.696-2.604s6.405,2.902,12.915,2.804c6.706-0.101,13.521-3.203,13.521-3.203s4.965,4.66,11.1,6.008    c6.177,1.357,11.502-5.606,11.502-5.606s7.73,1.494,10.291-4.407C97.064,41.516,93.075,32.489,93.075,32.489z M66.438,58.126    c0,0-1.845-0.681-3.43-1.603c-1.316-0.767-2.422-1.803-2.422-1.803s-0.207,1.53-0.544,2.529s-1,2.042-1,2.042    s-0.119-0.68-0.275-1.429c-0.195-0.94-0.45-1.99-0.602-1.941c-1.188,0.395-2.421,0.401-2.421,0.401s0.818,2.489,0.402,4.405    c-0.646,2.959-2.222,7.61-2.222,7.61s-1.627-3.662-2.219-6.008c-0.515-2.039-0.404-4.606-0.404-4.606s-2.624-0.08-5.044-0.401    c-2.097-0.275-4.037-0.802-4.037-0.802l1.009,3.807c0,0-1.816-0.758-3.228-2.002c-1.308-1.154-1.615-2.805-1.615-2.805    l-2.421-0.602c0,0,1.156,3,4.237,6.209C53,72.375,50.625,73.688,49.375,84.75c-0.438,4.829-1.538,9.285-2.389,11.479    c-0.631,1.627-3.834,2.806-3.834,2.806s0.99,0.8,5.046,0.8c1.918,0,7.303-0.962,9.52-1.138c1.252-0.101,3.101,0.38,4.438,0.399    c1.617,0.023,2.625-0.399,2.625-0.399s-4.922-1.392-5.65-3.005c-0.561-1.242-1.01-2.807-1.01-2.807s-1.434-5.572-0.246-18.322    C59.312,63.875,66.438,58.126,66.438,58.126z"/>
  </g>
</g>
</svg>

app/views/boroughs/_people.html.erb
<svg class="people" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" id="Layer_1" x="0px" y="0px" width="100px" height="100px" viewBox="0 0 100 100" enable-background="new 0 0 100 100" xml:space="preserve">
<circle cx="40.204" cy="43.474" r="5.476"/>
<path d="M66.502,53.686h-9.639c-1.702,0-3.084,1.24-3.084,2.942l-1.745,19.308c0,1.703,1.381,3.147,3.083,3.147h0.961l2.374,16.209  c0,1.037,0.843,1.753,1.882,1.753h2.7c1.038,0,1.879-0.716,1.879-1.753l2.375-16.209h0.962c1.704,0,3.085-1.444,3.085-3.147  l-1.749-19.308C69.586,54.926,68.205,53.686,66.502,53.686z"/>
<circle cx="61.684" cy="46.45" r="5.17"/>
<path d="M23.949,66.439h-6.803c-1.203,0-2.177,0.875-2.177,2.076l-1.232,8.381c0,1.201,0.974,2.222,2.177,2.222h0.679l1.675,16.69  c0,0.729,0.595,1.237,1.328,1.237h1.907c0.732,0,1.326-0.508,1.326-1.237l1.676-16.69h0.679c1.204,0,2.178-1.021,2.178-2.222  l-1.235-8.381C26.126,67.314,25.152,66.439,23.949,66.439z"/>
<circle cx="20.549" cy="61.331" r="3.651"/>
<path d="M83.328,73.271c0-1.002-0.813-1.731-1.814-1.731h-5.67c-1.003,0-1.814,0.729-1.814,1.731l-1.026,11.355  c0,1.002,0.813,1.854,1.813,1.854h0.565l1.396,9.535c0,0.607,0.494,1.03,1.104,1.03h1.591c0.608,0,1.105-0.423,1.105-1.03  l1.396-9.535h0.565c1.003,0,1.815-0.852,1.815-1.854L83.328,73.271z"/>
<circle cx="78.679" cy="67.283" r="3.042"/>
<path d="M46.322,51.298c-0.322-0.097-0.66-0.161-1.018-0.161H35.101c-1.805,0-3.266,1.313-3.266,3.115l-1.85,12.572  c0,1.801,1.462,3.332,3.266,3.332h1.019l2.512,25.033c0,1.098,0.892,1.854,1.991,1.854h2.86c1.1,0,1.991-0.758,1.991-1.854  l2.514-25.033h1.019c1.805,0,3.267-1.531,3.267-3.332l-0.205-1.391V36.037v-4.946c3.689,0.553,6.695,2.447,8.017,4.946h1.451  c1.578-2.989,5.576-5.113,10.26-5.113c4.679,0,8.676,2.125,10.259,5.113h0.303c0-17.077-13.157-31.071-29.89-32.415  c-0.041-1.429-1.202-2.576-2.641-2.576c-1.437,0-2.601,1.147-2.64,2.576c-16.73,1.344-29.89,15.338-29.89,32.415h0.306  c1.58-2.989,5.575-5.113,10.258-5.113c4.683,0,8.678,2.125,10.257,5.113h1.452c1.39-2.629,4.651-4.588,8.602-5.021v5.021v15.261"/>
</svg>

app/views/boroughs/index.html.haml
%h1 Boroughs#index
- @boroughs.each do |borough|
  = link_to borough.name, borough_path(borough)
  %br

app/views/boroughs/show.html.haml
= render 'borough'

app/views/clients/index.html.haml
-@clients.each do |client|
  = client.name

app/views/layouts/application.html.erb
!!!
%html
  %head
    %title OverThere
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    = yield

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title OverThere
    = yield :templates
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    / %audio{:autoplay => "autoplay", :hidden => "hidden"} <source src="song.mp3" type="audio/mpeg"">
  %body
    = yield

app/views/main/index.html.haml
.hero
  .hero-inner
    .hero-logo
      = render 'logo'
    .hero-copy
      %h1 Over There
      %p Are you over it? What's it like over there? Find out exactly how hip your area is, over here!   
      .search-bar
        .search-and-submit
          =form_for @postcode do |f|
            = f.search_field :postcode, placeholder: "Search By Postcode"
            %button{type: "submit"}
              %img{src: "https://raw.githubusercontent.com/Magnus-G/Random/master/search-icon-black.png"}
    
      %p.notice= notice